#!bin/bash

# This script is used for converting StaMPS-output files (which can be generated by stamps2gmt.m) to PSO files, including generating .inc, .azi and converting LOS to PHS which is needed as input data in PSO.
# files you need to prepare: 
# 1. EQA_$reference.dem_par
# 2. lv_theta
# 3. lv_phi
# NOTE: if ALOS or other band data used, you should change this script accordingly

reference=20190306
FileFromStamps=INSAR_T072A_83.unw
OutName=INSAR_T072A
# the unit of StamPS files, mm or cm, which is useful for converting los to phase
unit=mm

####################################################################################
North=`awk '$1 == "corner_lat:" {print $2}' EQA.$reference.dem_par`
West=`awk '$1 == "corner_lon:" {print $2}' EQA.$reference.dem_par`
posty=`awk '$1 == "post_lat:"   {print $2}' EQA.$reference.dem_par`
postx=`awk '$1 == "post_lon:"   {print $2}' EQA.$reference.dem_par`
width=`awk '$1 == "width:"      {print $2}' EQA.$reference.dem_par`
line=`awk '$1 == "nlines:"     {print $2}' EQA.$reference.dem_par`
South=`echo ${North} ${line}  ${posty} | awk '{printf "%.8f", $1+($2-1)*$3}'`
East=`echo ${West}  ${width} ${postx} | awk '{printf "%.8f", $1+($2-1)*$3}'`


##############
swap_bytes lv_theta lv_theta.phase_swap 4
# gmt xyz2grd lv_theta.phase_swap -Glv_theta_f.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf -di0
gmt xyz2grd lv_theta.phase_swap -Glv_theta_f.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf
gmt grdsample lv_theta_f.grd -Glv_theta.grd -I3s
gmt grdmath 90 lv_theta.grd 3.1415926 DIV 180 MUL SUB = lv_theta.grd
# gmt grd2xyz lv_theta.grd -ZTLf -do0 > $OutName.inc
gmt grd2xyz lv_theta.grd -ZTLf > $OutName.inc

swap_bytes lv_phi lv_phi.phase_swap 4
# gmt xyz2grd lv_phi.phase_swap -Glv_phi_f.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf -di0
gmt xyz2grd lv_phi.phase_swap -Glv_phi_f.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf
gmt grdsample lv_phi_f.grd -Glv_phi.grd -I3s
gmt grdmath -90 lv_phi.grd 3.1415926 DIV 180 MUL SUB = lv_phi.grd
# gmt grd2xyz lv_phi.grd -ZTLf -do0 > $OutName.azi
gmt grd2xyz lv_phi.grd -ZTLf > $OutName.azi

# pay attention to -ZLTf should be ignored in xyz2grd (default = -ZTLa)
# gmt xyz2grd $FileFromStamps -Gunw_los.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -di0
gmt xyz2grd $FileFromStamps -Gunw_los.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s
# convert LOS from StaMPS to PHS which is required in pso, if the unit is mm, then it should be 27.8 for sentinel-1, if the unit is cm, then it should be 2.78 for S1
if [ "$unit" == "mm" ]; then
	gmt grdmath unw_los.grd 27.8 DIV 2 MUL 3.141592653 MUL NEG = unw_phs.grd
elif [ "$unit" == "cm" ]; then
	gmt grdmath unw_los.grd 2.78 DIV 2 MUL 3.141592653 MUL NEG = unw_phs.grd
else
	echo "Please input the unit of StaMPS files!" & exit
fi
gmt grdsample unw_phs.grd -Gunw.grd -I3s
# gmt grd2xyz unw.grd -ZTLf -do0 > $OutName.unw
gmt grd2xyz unw.grd -ZTLf > $OutName.unw

width=`gmt grdinfo lv_theta.grd -C | awk '{print $10}'`
line=`gmt grdinfo lv_theta.grd -C | awk '{print $11}'`
West=`gmt grdinfo lv_theta.grd -C | awk '{print $2}'`
North=`gmt grdinfo lv_theta.grd -C | awk '{print $5}'`

ymax=`echo $line | awk '{print $1-1}'`
xmax=`echo $width | awk '{print $1-1}'`

echo WIDTH                                    $width > $OutName.unw.rsc
echo FILE_LENGTH                              $line >> $OutName.unw.rsc
echo XMIN                                     0 >> $OutName.unw.rsc
echo XMAX                                     $xmax >> $OutName.unw.rsc
echo YMIN                                     0 >> $OutName.unw.rsc
echo YMAX                                     $ymax >> $OutName.unw.rsc
echo RLOOKS                                   1 >> $OutName.unw.rsc
echo ALOOKS                                   1 >> $OutName.unw.rsc
echo X_FIRST                                  $West >> $OutName.unw.rsc
echo X_STEP                                   8.33333333E-04 >> $OutName.unw.rsc
echo X_UNIT                                   degrees >> $OutName.unw.rsc
echo Y_FIRST                                  $North >> $OutName.unw.rsc
echo Y_STEP                                   -8.3333333E-04 >> $OutName.unw.rsc
echo Y_UNIT                                   degrees >> $OutName.unw.rsc
echo WAVELENGTH                               0.0555041577 >> $OutName.unw.rsc
echo MODEL                                    insar >> $OutName.unw.rsc

#mv $OutName.unw geo_$OutName_dem_flat.unw
cp -f $OutName.unw.rsc $OutName.inc.rsc
cp -f $OutName.unw.rsc $OutName.azi.rsc
#cp -f $OutName.unw.rsc geo_$OutName_dem_flat.unw.rsc
#cp -f $OutName.unw.rsc geo_$OutName_dem_flat_roi.unw.rsc

##############
rm -rf *swap *grd gmt*
# end

