#!/bin/bash

# this script is used for unwrapping after the Differential Interferometry
# run this script under project DIR $procdir
# Zelong Guo @GFZ, Potsdam
# First Version: 14.01.2021

#reference=20171107
#slave=20171119
#width=$(grep 'range_samples:' $reference.rmli.par | awk '{print $2}')

reference=$1
slave=$2

procdir=$(echo "$PWD")

width=$(cat $procdir/subset/$reference.rmli.par | grep 'range_samples:' | awk '{print $2}')
waveleg=$(cat $procdir/coreg/$reference.rslc.par | grep 'radar_frequency:' | awk '{print $2}' | awk '{printf "%.1f", 300000000/$1*100}')
half_waveleg=$(echo "$waveleg" | awk '{printf "%.1f", $1/2}')
double_waveleg=$(echo "$waveleg" | awk '{printf "%.1f", $1*2}')
quadr_waveleg=$(echo "$waveleg" | awk '{printf "%.1f", $1*4}')

mkdir -p unw
cd unw

ln -s $procdir/subset/${reference}_${slave}.diff ./

# filtering
adf ${reference}_${slave}.diff tmp ${reference}_${slave}.diff2.cc $width 0.2 128 7 16 0 0 0.25;
adf tmp tmp1 ${reference}_${slave}.diff2.cc $width 0.3 64 7 8 0 0 0.25;
adf tmp1 ${reference}_${slave}.diff2.flt ${reference}_${slave}.diff2.cc $width 0.4 32 7 4 0 0 0.25;

#rasmph_pwr ${reference}_${slave}.diff2.flt $reference.rmli $width - - - 1 1 1. .35 1 ${reference}_${slave}.diff2.flt.bmp
rasmph_pwr ${reference}_${slave}.diff2.flt $reference.rmli $width - - - 1 1 1. .35 1 


:<<cc
rascc_mask ${reference}_${slave}.diff2.cc $reference.rmli $width 1 1 0 1 1 .25 .1
rascc_mask_thinning ${reference}_${slave}.diff2.cc_mask.bmp ${reference}_${slave}.diff2.cc $width ${reference}_${slave}.diff2.cc.ras_thinning.ras 3 .3 .4 .5 

#rascc_mask_thinning  20171107_20171119.diff2.cc_mask.bmp ${reference}_${slave}.diff2.cc $width ${reference}_${slave}.diff2.cc.mask_thinning.ras 5 .3 .4 .5 .6 .7 

mcf ${reference}_${slave}.diff2.flt ${reference}_${slave}.diff2.cc ${reference}_${slave}.diff2.cc.ras_thinning.ras ${reference}_${slave}.diff2.flt.unw $width 1 0 0 - - 1 1 600 - - 0
rasmph_pwr ${reference}_${slave}.diff2.flt.unw $reference.rmli $width - - - - - .5 - - - - ${reference}_${slave}.diff2.flt.unw.bmp
#rasmph_pwr 20171106_20171118.diff2.flt.unw 20171106.rmli 2709 - - - - - 1 - - - - 20171106_20171118.diff2.flt.unw.bmp
cc

# change it please
#mcf ${reference}_${slave}.diff2.flt ${reference}_${slave}.diff2.cc - ${reference}_${slave}.diff2.flt.unw $width 1 0 0 - - 1 1 600 - - 0
#mcf ${reference}_${slave}.diff2.flt ${reference}_${slave}.diff2.cc - ${reference}_${slave}.diff2.flt.unw $width - - - - - - - - 5100 2900 
mcf ${reference}_${slave}.diff2.flt ${reference}_${slave}.diff2.cc - ${reference}_${slave}.diff2.flt.unw $width - - - - - - - - 270 208
dw=`cat $procdir/multi_looking/EQA.$reference.dem_par | grep "width" | awk '{print $2}'`
geocode_back ${reference}_${slave}.diff2.flt.unw $width $procdir/multi_looking/EQA.$reference.lt_fine ${reference}_${slave}.diff2.flt.unw.geo $dw - - 0 

#rasmph_pwr ${reference}_${slave}.diff2.flt.unw.geo - $dw  - - - - - 1 - - - - ${reference}_${slave}.diff2.flt.unw.${half_waveleg}cm.png
#rasmph_pwr ${reference}_${slave}.diff2.flt.unw.geo $procdir/multi_looking/EQA.$reference.mli $dw  - - - - - 1 - - - - ${reference}_${slave}.diff2.flt.unw.${half_waveleg}cm.bmp
rasmph_pwr ${reference}_${slave}.diff2.flt.unw.geo - $dw  
rasmph_pwr ${reference}_${slave}.diff2.flt.unw.geo $procdir/multi_looking/EQA.$reference.mli $dw

#convert -transparent black ${reference}_${slave}.diff2.flt.unw.geo.bmp ${reference}_${slave}.diff2.flt.unw.geo.png
#mk_kml ../EQA.dem_par ${reference}_${slave}.diff2.flt.unw.geo.png ${reference}_${slave}.diff2.flt.unw.geo.kml

rasmph_pwr ${reference}_${slave}.diff2.flt.unw.geo $procdir/multi_looking/EQA.$reference.mli $dw  - - - - - .5 - - - - ${reference}_${slave}.diff2.flt.unw.${waveleg}cm.bmp
rasmph_pwr ${reference}_${slave}.diff2.flt.unw.geo $procdir/multi_looking/EQA.$reference.mli $dw  - - - - - .25 - - - - ${reference}_${slave}.diff2.flt.unw.${double_waveleg}cm.bmp
rasmph_pwr ${reference}_${slave}.diff2.flt.unw.geo $procdir/multi_looking/EQA.$reference.mli $dw  - - - - - .125 - - - - ${reference}_${slave}.diff2.flt.unw.${quadr_waveleg}cm.bmp

cd $procdir
