#!/bin/bash

if [ "$1" == "--help" ] || [ "$1" == "-help" ] || [ "$1" == "-h" ] || [ "$#" -lt "1"  ]; then
	cat<<END && exit 1 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
 Generate unw_utm, inc and azi files by swapping byte  
 Downsample the files with posting 8.33333333E-04 degree, i.e. 3 arc sencind
 FINAL DIR will be created.

  Program:		`basename $0`
  usage:		`basename $0` <MASTER_SLAVE>
  <MASTER_SLAVE>:	YYYYMMDD_YYYYMMDD; e.g. 20171106_20171118
            

	    Run under procdir     
            CURRENT DIR: $PWD

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
END
fi

mkdir -p FINAL
cp UNW/*/*.unw_utm FINAL/
cp SIM/*.utm.dem FINAL/
cp SIM/*.utm.dem.par FINAL/
cp SIM/lv_theta FINAL/
cp SIM/lv_phi FINAL/
cd FINAL

####################################################################################
North=`awk '$1 == "corner_lat:" {print $2}' $1.utm.dem.par`
West=`awk '$1 == "corner_lon:" {print $2}' $1.utm.dem.par`
posty=`awk '$1 == "post_lat:"   {print $2}' $1.utm.dem.par`
postx=`awk '$1 == "post_lon:"   {print $2}' $1.utm.dem.par`
width=`awk '$1 == "width:"      {print $2}' $1.utm.dem.par`
line=`awk '$1 == "nlines:"     {print $2}' $1.utm.dem.par`
South=`echo ${North} ${line}  ${posty} | awk '{printf "%.8f", $1+($2-1)*$3}'` 
East=`echo ${West}  ${width} ${postx} | awk '{printf "%.8f", $1+($2-1)*$3}'`


##############
swap_bytes lv_theta lv_theta.phase_swap 4
gmt xyz2grd lv_theta.phase_swap -Glv_theta_f.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf -di0
gmt grdsample lv_theta_f.grd -Glv_theta.grd -I3s
# $1.elev for GACOS
gmt grd2xyz lv_theta.grd -ZTLf -do0 > $1.elev
gmt grdmath 90 lv_theta.grd 3.1415926 DIV 180 MUL SUB = lv_theta.grd
gmt grd2xyz lv_theta.grd -ZTLf -do0 > $1.inc

swap_bytes lv_phi lv_phi.phase_swap 4
gmt xyz2grd lv_phi.phase_swap -Glv_phi_f.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf -di0
gmt grdsample lv_phi_f.grd -Glv_phi.grd -I3s
gmt grdmath -90 lv_phi.grd 3.1415926 DIV 180 MUL SUB = lv_phi.grd
gmt grd2xyz lv_phi.grd -ZTLf -do0 > $1.azi

swap_bytes $1.unw_utm unw.phase_swap 4
gmt xyz2grd unw.phase_swap -Gunw_f.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf -di0
gmt grdsample unw_f.grd -Gunw.grd -I3s
gmt grd2xyz unw.grd -ZTLf -do0 > $1.unw

swap_bytes $1.utm.dem dem.phase_swap 4
gmt xyz2grd dem.phase_swap -Gdem_f.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf -di0
gmt grdsample dem_f.grd -Gdem.grd -I3s
gmt grd2xyz dem.grd -ZTLf -do0 > $1.dem

width=`gmt grdinfo lv_theta.grd -C | awk '{print $10}'`
line=`gmt grdinfo lv_theta.grd -C | awk '{print $11}'`
West=`gmt grdinfo lv_theta.grd -C | awk '{print $2}'`
North=`gmt grdinfo lv_theta.grd -C | awk '{print $5}'`

ymax=`echo $line | awk '{print $1-1}'`
xmax=`echo $width | awk '{print $1-1}'` 

echo WIDTH                                    $width > $1.unw.rsc                           
echo FILE_LENGTH                              $line >> $1.unw.rsc                           
echo XMIN                                     0 >> $1.unw.rsc                              
echo XMAX                                     $xmax >> $1.unw.rsc                          
echo YMIN                                     0 >> $1.unw.rsc                              
echo YMAX                                     $ymax >> $1.unw.rsc                          
echo RLOOKS                                   1 >> $1.unw.rsc                              
echo ALOOKS                                   1 >> $1.unw.rsc                              
echo X_FIRST                                  $West >> $1.unw.rsc               
echo X_STEP                                   8.33333333E-04 >> $1.unw.rsc               
echo X_UNIT                                   degrees >> $1.unw.rsc                        
echo Y_FIRST                                  $North >> $1.unw.rsc              
echo Y_STEP                                   -8.3333333E-04 >> $1.unw.rsc              
echo Y_UNIT                                   degrees >> $1.unw.rsc                        
echo WAVELENGTH                               0.0555041577 >> $1.unw.rsc              
echo MODEL                                    insar >> $1.unw.rsc

# $1.elev for GACOS
echo WIDTH				      $width > $1.elev.rsc 
echo FILE_LENGTH 			      $line >> $1.elev.rsc 
echo XMIN        			       0 >> $1.elev.rsc
echo XMAX        			      $width > $1.elev.rsc 
echo YMIN        			       0 >> $1.elev.rsc
echo YMAX        			      $line >> $1.elev.rsc
echo X_FIRST     			      $West >> $1.elev.rsc 
echo Y_FIRST     			      $North >> $1.elev.rsc 
echo X_STEP      			      0.00083333 >> $1.elev.rsc
echo Y_STEP      			      -0.00083333 >> $1.elev.rsc
echo X_UNIT      			       degres
echo Y_UNIT      			       degres

mv $1.unw geo_$1_dem_flat.unw
cp -f $1.unw.rsc $1.inc.rsc
cp -f $1.unw.rsc $1.azi.rsc
cp -f $1.unw.rsc geo_$1_dem_flat.unw.rsc
#cp -f $1.unw.rsc geo_$1_dem_flat_roi.unw.rsc

##############
rm -rf *swap *grd $1.unw.rsc gmt*
# end
