#!/bin/bash

if [ "$1" == "--help" ] || [ "$1" == "-help" ] || [ "$1" == "-h" ] || [ "$#" -lt "1"  ]; then
	cat<<END && exit 1 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
 Generate unw_utm, inc and azi files by swapping byte  
 FINAL DIR will be created.

  Program:		`basename $0`
  usage:		`basename $0` <MASTER_SLAVE>
  <MASTER_SLAVE>:	YYYYMMDD_YYYYMMDD; e.g. 20171106_20171118
            

	    Run under procdir     
            CURRENT DIR: $PWD

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
END
fi

mkdir -p FINAL
cp UNW/*/*.unw_utm FINAL/
cp SIM/*.utm.dem.par FINAL/
cp SIM/lv_theta FINAL/
cp SIM/lv_phi FINAL/
cd FINAL

####################################################################################
North=`awk '$1 == "corner_lat:" {print $2}' $1.utm.dem.par`
West=`awk '$1 == "corner_lon:" {print $2}' $1.utm.dem.par`
posty=`awk '$1 == "post_lat:"   {print $2}' $1.utm.dem.par`
postx=`awk '$1 == "post_lon:"   {print $2}' $1.utm.dem.par`
width=`awk '$1 == "width:"      {print $2}' $1.utm.dem.par`
line=`awk '$1 == "nlines:"     {print $2}' $1.utm.dem.par`
South=`echo ${North} ${line}  ${posty} | awk '{printf "%.8f", $1+($2-1)*$3}'` 
East=`echo ${West}  ${width} ${postx} | awk '{printf "%.8f", $1+($2-1)*$3}'`


##############
swap_bytes lv_theta lv_theta.phase_swap 4
# gmt xyz2grd lv_theta.phase_swap -Glv_theta.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf -di0
gmt xyz2grd lv_theta.phase_swap -Glv_theta.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf
gmt grdmath 90 lv_theta.grd 3.1415926 DIV 180 MUL SUB = lv_theta.grd
# gmt grd2xyz lv_theta.grd -ZTLf -do0 > $1.inc
gmt grd2xyz lv_theta.grd -ZTLf > $1.inc

swap_bytes lv_phi lv_phi.phase_swap 4
# gmt xyz2grd lv_phi.phase_swap -Glv_phi.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf -di0
gmt xyz2grd lv_phi.phase_swap -Glv_phi.grd -Ddegree/degree/cm/1/0/=/= -R${West}/${East}/${South}/${North} -I1s -ZTLf
gmt grdmath -90 lv_phi.grd 3.1415926 DIV 180 MUL SUB = lv_phi.grd
# gmt grd2xyz lv_phi.grd -ZTLf -do0 > $1.azi
gmt grd2xyz lv_phi.grd -ZTLf > $1.azi

ymax=`echo $line | awk '{print $1-1}'`
xmax=`echo $width | awk '{print $1-1}'` 

echo WIDTH                                    $width > $1.unw.rsc                           
echo FILE_LENGTH                              $line >> $1.unw.rsc                           
echo XMIN                                     0 >> $1.unw.rsc                              
echo XMAX                                     $xmax >> $1.unw.rsc                          
echo YMIN                                     0 >> $1.unw.rsc                              
echo YMAX                                     $ymax >> $1.unw.rsc                          
echo RLOOKS                                   1 >> $1.unw.rsc                              
echo ALOOKS                                   1 >> $1.unw.rsc                              
echo X_FIRST                                  $West >> $1.unw.rsc               
echo X_STEP                                   $postx >> $1.unw.rsc               
echo X_UNIT                                   degrees >> $1.unw.rsc                        
echo Y_FIRST                                  $North >> $1.unw.rsc              
echo Y_STEP                                   $posty >> $1.unw.rsc              
echo Y_UNIT                                   degrees >> $1.unw.rsc                        
echo WAVELENGTH                               0.0555041577 >> $1.unw.rsc              
echo MODEL                                    insar >> $1.unw.rsc


swap_bytes $1.unw_utm geo_$1_dem_flat.unw 4
cp -f $1.unw.rsc $1.inc.rsc
cp -f $1.unw.rsc $1.azi.rsc
cp -f $1.unw.rsc geo_$1_dem_flat.unw.rsc
cp -f $1.unw.rsc geo_$1_dem_flat_roi.unw.rsc

##############
rm -rf lv_phi.grd lv_phi.phase_swap lv_theta.grd lv_theta.phase_swap dinsar.log $1.unw.rsc
# end
